package com.austria.logistics.commands.enums;

public enum CommandType {
    ASSIGNLOCATION,
    ASSIGNPACKAGE,
    ASSIGNTRUCK,
    CREATEPACKAGE,
    CREATEROUTE,
    SHOWPACKAGES,
    SHOWPACKAGE,
    SHOWROUTE,
    SHOWTRUCKS,
    SHOWUSERS,
    UNASSIGNTRUCK,
    UNASSIGNPACKAGE,
    UNASSIGNLOCATION,
    LOGIN,
    LOGOUT,
    READMAIL,
    REGISTER,
    SAVE,
    LOAD
}
